# Configuration to create a complete website locally, containing of the docs
# and the exampleSite.
#
# 1. Build the docs by either `hugo` or `hugo server`
# 2. Build the exampleSite by `hugo --environment dev` or `hugo server --environment dev
#`
# After that, a complete website is available in the docs/public folder
# and can be used from the file system. The links between both projects
# will not work with `hugo server`, the pages need to be visited
# separately, adding different ports.

# Standard adjustments for deveolpment, to make this site work
baseURL = 'https://example.com/exampleSite/'
relativeURLs = false
publishDir = '../docs/public/exampleSite'
